// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeXMVS_vAoIga6kZAAwdEsS9GjzdfWkwA',
    appId: '1:936171168732:web:07666c0593ee8150e46519',
    messagingSenderId: '936171168732',
    projectId: 'rent-ride-81781',
    authDomain: 'rent-ride-81781.firebaseapp.com',
    storageBucket: 'rent-ride-81781.appspot.com',
    measurementId: 'G-S7EP9PPGVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXEcqW77zuIaUyu0_zXBf2O_rHf4s3JYw',
    appId: '1:936171168732:android:e4371eb9c8b2552ae46519',
    messagingSenderId: '936171168732',
    projectId: 'rent-ride-81781',
    storageBucket: 'rent-ride-81781.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMU5kgd2omgtEk27-mR0VhlOCRPdKyWN8',
    appId: '1:936171168732:ios:ef85ea4a3e8da971e46519',
    messagingSenderId: '936171168732',
    projectId: 'rent-ride-81781',
    storageBucket: 'rent-ride-81781.appspot.com',
    iosBundleId: 'com.example.rentRideCs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMU5kgd2omgtEk27-mR0VhlOCRPdKyWN8',
    appId: '1:936171168732:ios:ef85ea4a3e8da971e46519',
    messagingSenderId: '936171168732',
    projectId: 'rent-ride-81781',
    storageBucket: 'rent-ride-81781.appspot.com',
    iosBundleId: 'com.example.rentRideCs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeXMVS_vAoIga6kZAAwdEsS9GjzdfWkwA',
    appId: '1:936171168732:web:2f4b905b0bcfe192e46519',
    messagingSenderId: '936171168732',
    projectId: 'rent-ride-81781',
    authDomain: 'rent-ride-81781.firebaseapp.com',
    storageBucket: 'rent-ride-81781.appspot.com',
    measurementId: 'G-PZ03LVE5QP',
  );
}
